loadout_list =
{
    {
        name = "K.E. TYPE",
        folder = "ke",
        -- NOTE: Usually the game uses ARGB format for colours, but the cape colour uses ABGR here instead
        cape_color = 0xff9a6f9b,
        cape_color_edge = 0xff76547f,
        items = 
        {
            "mods/keopgamemode/files/ke/wands/wand_1.xml",
            "mods/keopgamemode/files/ke/wands/wand_2.xml",
            "mods/keopgamemode/files/ke/wands/wand_3.xml",
            {
            "mods/keopgamemode/files/                              i/potion_slime.xml",
            amount = 2,
            },
        },
        perks =
        {
            "ADVENTURER",
            "ALWAYS_CAST",
            "ANGRY_GHOST",
            "ATTRACT_ITEMS",
            "BLEED_OIL",
            "BREATH_UNDERWATER",
            "DESTRUCTION_ENHANCEMENT",
            "DESTRUCTIVE_SPELLS",
            "DISSOLVE_POWDERS",
            "EDIT_WANDS_EVERYWHERE",
            "EXPLODING_CORPSES",
            "EXPLODING_GOLD",
            "EXTRA_MONEY",
            "EXTRA_MONEY_TRICK_KILL",
            "EXTRA_PERK",
            "EXTRA_SLOTS",
            "EXTRA_WAND_SLOT",
            "FAST_PROJECTILES",
            "FASTER_LEVITATION",
            "FASTER_SWIMMING",
            "FASTER_WANDS",
            "FUNGAL_DISEASE",
            "GAS_FIRE",
            "GLOBAL_GORE",
            "GOLD_IS_FOREVER",
            "GOLDEN_I",
            "HEARTS_MORE_EXTRA_HP",
            "HELPER_ORB",
            "HOMUNCULUS",
            "HOVER_BOOST",
            "HUNGRY_GHOST",
            "INVISIBILITY",
            "IRON_STOMACH",
            "KNOCKBACK_CONTROL",
            -- "LEGGY_FEET",
            -- "ATTACK_FEET",
            "LIQUID_MOVEMENT",
            "LOW_GRAVITY",
            "LOWER_SPREAD",
            "MANA_DISCOUNT",
            "MANA_FROM_KILLS",
            "MAP",
            "MEGA_BEAM_STONE",
            "MELT",
            "MOON_RADAR",
            "MOVEMENT_FASTER",
            "MYSTERY_EGG",
            "MYSTERY_EGGPLANT",
            "NO_DAMAGE_FLASH",
            "NO_MORE_KNOCKBACK",
            "NO_MORE_SHUFFLE",
            "NO_PLAYER_KNOCKBACK",
            "ORBIT",
            "PERMANENT_FLYING",
            "PERSONAL_RAINCLOUD",
            "PROJECTILE_DUPLICATE",
            "PROJECTILE_EATER_SECTOR",
            "PROJECTILE_HOMING",
            "PROJECTILE_REPULSION",
            "PROJECTILE_REPULSION_SECTOR",
            "PROJECTILE_SLOW_FIELD",
            "PROTECTION_ELECTRICITY",
            "PROTECTION_EXPLOSION",
            "PROTECTION_FIRE",
            "PROTECTION_FREEZE",
            "PROTECTION_MELEE",
            "PROTECTION_RADIOACTIVITY",
            "RADAR_ENEMY",
            "RADAR_ITEM",
            "RADAR_MOON",
            "RADAR_WAND",
            "REMOVE_FOG_OF_WAR",
            "RESPAWN",
            "REVEAL_SECRETS",
            "REVENGE_EXPLOSION",
            "REVENGE_TENTACLE",
            "REVERSE_SLOWDOWN",
            "SAVING_GRACE",
            "SHIELD",
            "SPEED_DIVER",
            "SPELL_DUPLICATION",
            "STAINLESS_ARMOUR",
            "STRONG_KICK",
            "TELEKINESIS",
            "TELEPORTITIS_DODGE",
            "TRICK_BLOOD_MONEY",
            "UNLIMITED_SPELLS",
            "VAMPIRISM",
            "VISION",

            "EXTRA_HP",
            "EXTRA_HP",
            "EXTRA_HP",
            "EXTRA_HP",
        },
    }
}
